version: "3"

services:
  terraform:
    image: hashicorp/terraform:1.3.5
    volumes:
      - ./:/workdir
    working_dir: "/workdir/terraform"
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
